version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: excel-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - excel-network

networks:
  excel-network:
    driver: bridge

volumes:
  minio_data:
    driver: local
